import{_ as e,d as t,f as n,i as r,l as i,o as a,r as o,t as s,u as c}from"./src-BuinseSQ.js";var l=t(),u=e(n(),1),d=i(),f=({buttons:e,className:t,style:n})=>(0,d.jsx)(`div`,{className:`flex justify-center text-sm ${t??``}`,style:n,children:(0,d.jsx)(`div`,{className:`border border-gray-200 p-1 rounded-full flex gap-4`,children:e.map((e,t)=>(0,d.jsx)(`button`,{className:`px-4 py-3 rounded-full transition-colors hover:bg-black/10${e.selected?` bg-black/4`:``} ${e.className??``}`,type:`button`,onClick:t=>{t.preventDefault(),e.onClick()},children:e.text},`button-group-${t}`))})}),p=({examples:e})=>{let[t,n]=(0,u.useState)(0),r=(0,u.useRef)(null),i=e[t].href;return(0,u.useEffect)(()=>{if(`application/pdf`in navigator.mimeTypes){let e=r.current;Array.from(e.childNodes).forEach(t=>e.removeChild(t));let t=document.createElement(`iframe`);t.className=`w-full h-[600px]`,t.src=i,e.appendChild(t),e.className=``}else (async()=>{if(!(`__pdfjsLoading`in window)){let e=document.createElement(`script`);e.type=`module`,e.src=`//unpkg.com/pdfjs-dist@5.4.54/build/pdf.min.mjs`,document.head.appendChild(e);let{promise:t,resolve:n}=Promise.withResolvers();e.onload=()=>n(),window.__pdfjsLoading=t}await window.__pdfjsLoading;let e=window.pdfjsLib;e.GlobalWorkerOptions.workerSrc=`//unpkg.com/pdfjs-dist@5.4.54/build/pdf.worker.min.mjs`;let t=r.current;Array.from(t.childNodes).forEach(e=>t.removeChild(e));let n=await e.getDocument(i).promise,a=Array(n.numPages).fill(0).map(()=>document.createElement(`canvas`));a.forEach(e=>{e.classList.add(`w-full`),t.appendChild(e)}),await Promise.all(a.map(async(e,t)=>{let r=await n.getPage(t+1),i=r.getViewport({scale:window.devicePixelRatio??2});return e.height=i.height,e.width=i.width,r.render({canvas:e,canvasContext:e.getContext(`2d`),viewport:i}).promise}))})()},[i]),(0,d.jsxs)(d.Fragment,{children:[e.length>1&&(0,d.jsx)(f,{buttons:e.map((e,r)=>({text:e.title,onClick:()=>n(r),selected:r===t})),className:`w-full`,style:{width:`min(100vw, 90rem)`,marginLeft:`calc((100% - min(100vw, 90rem)) / 2)`}}),(0,d.jsx)(`div`,{className:`flex flex-col gap-2 max-h-[600px] overflow-y-scroll`,ref:r})]})};function m(e){let t={a:`a`,code:`code`,h2:`h2`,img:`img`,li:`li`,p:`p`,strong:`strong`,ul:`ul`,...e.components};return(0,d.jsxs)(d.Fragment,{children:[(0,d.jsx)(t.p,{children:`We introduce GLM-5.3-Flash, the first natively multimodal model in the GLM-5 series. With 320B total parameters and just 18B active parameters, it outperforms GLM-5.2 across benchmarks and real-world workloads at one-tenth the price, while approaching Claude Opus 4.8 on coding and agentic benchmarks.`}),`
`,(0,d.jsx)(t.p,{children:`GLM-5.3-Flash incorporates several architectural improvements over GLM-5. For the first time, we introduce a hybrid architecture combining sparse and linear attention, sharply reducing long-context serving costs while preserving precise long-context capabilities. It also adopts Manifold-Constrained Hyper-Connections (mHC) to further improve scaling efficiency. Combined with our latest 30T-token multimodal pre-training corpus, these changes let GLM-5.3-Flash produce more intelligence with less compute.`}),`
`,(0,d.jsxs)(t.p,{children:[`Before release, we tested GLM-5.3-Flash anonymously as `,(0,d.jsx)(t.code,{children:`ox-alpha`}),` on OpenCode and OpenRouter to gather user feedback. It quickly became the most popular model of the week — with all of this traffic served on Chinese AI chips.`]}),`
`,(0,d.jsxs)(`div`,{style:{display:`flex`,gap:10},children:[(0,d.jsx)(`div`,{style:{width:`48%`},children:(0,d.jsx)(`img`,{src:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/ryTOUL3vGe.png`,style:{width:`100%`}})}),(0,d.jsx)(`div`,{style:{width:`52%`},children:(0,d.jsx)(`img`,{src:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/S10CTLhwzg.png`,style:{width:`100%`}})})]}),`
`,(0,d.jsx)(t.h2,{children:`Competitive Performance at Flash Cost`}),`
`,(0,d.jsx)(t.p,{children:`GLM-5.3-Flash pushes the Pareto frontier of the Artificial Analysis Intelligence Index v4.1.1, scoring 57 at just $0.045 per task (discounted) — a level of intelligence previously only available at roughly 10× the cost. This makes it a highly competitive default choice for a broad range of workloads.`}),`
`,(0,d.jsx)(t.p,{children:(0,d.jsx)(t.img,{src:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/Sy_ehD3wzx.png`,alt:`c2ea01fd1ee01e0ff054754a2ad9e644`})}),`
`,(0,d.jsx)(t.p,{children:`Across six coding and agentic benchmarks, GLM-5.3-Flash consistently outperforms GLM-5.2, often by a wide margin — 63.4 vs. 46.2 on DeepSWE v1.1 and 48.8 vs. 26.2 on AutomationBench — while approaching Claude Opus 4.8 overall.`}),`
`,(0,d.jsx)(t.p,{children:(0,d.jsx)(t.img,{src:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/rJG_RLhPzl.png`,alt:`img_v3_0214u_921edf4e-06c8-48ea-bffe-cdf2b79a0a6g`})}),`
`,(0,d.jsx)(t.p,{children:`This holds on our in-house coding evaluation as well: on Z.ai Code Bench v1.0 (run on Claude Code 2.1.207), GLM-5.3-Flash clearly outperforms GLM-5.2 at every effort level, and at max effort nearly matches Claude Opus 4.8 (29.0 vs. 29.5).`}),`
`,(0,d.jsx)(t.p,{children:(0,d.jsx)(t.img,{src:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/H1hAKXnDMx.png`,alt:`img_v3_0214u_eef3c372-bc89-44cd-9ec3-919ff63bac0g`})}),`
`,(0,d.jsx)(t.h2,{children:`Architecture for Extreme Efficiency`}),`
`,(0,d.jsx)(t.p,{children:(0,d.jsx)(t.img,{src:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/HyqVZw2wze.png`,alt:`img_v3_0214u_c34ae85d-2955-4bf5-9102-f22054c6f08g`})}),`
`,(0,d.jsx)(t.p,{children:`Compared with the GLM-4.5 series, GLM-5.3-Flash is specifically designed for ultra-low-cost inference. Despite a similar total parameter count (320B vs. 355B), it nearly halves both the activated parameter count (18B vs. 32B) and the number of layers (45 vs. 92).`}),`
`,(0,d.jsx)(t.p,{children:`To minimize attention costs in long-context scenarios, we use a hybrid architecture combining linear and sparse attention. Linear attention captures local dependencies through state modeling, while sparse attention retrieves relevant global context through a lightweight indexer. To further reduce the latency and memory overhead of the indexer at a 1M-token context length, we introduce IndexPool, which compresses four indexer key vectors into one through weighted pooling.`}),`
`,(0,d.jsx)(t.p,{children:`To illustrate the efficiency of our architecture, we compare the per-token compute and KV cache size of GLM-5.3-Flash against GLM-5.3 and two recent open models DeepSeek-V4-Flash and Kimi-K3. For a fair comparison among different scales, we calculate the attention compute per head per layer and average KV cache size per layer (BF16). Compared with GLM-5.3, GLM-5.3-Flash reduces the attention compute and KV cache size by factors of 3.0x and 4.4x. GLM-5.3-Flash has the lowest attention compute among all models compared. The KV cache size is still slightly larger than Kimi-K3 and DeepSeek-V4-Flash, leaving further room for improvement.`}),`
`,(0,d.jsx)(t.p,{children:`The overall architecture improvements, combined with optimized pre-training corpus, enable GLM-5.3-Flash to produce more intelligence with less compute.
In the table below we show the evaluation results of the base model of GLM-5.3-Flash, comparing with our previous base models and DeepSeek-V4-Flash-Base. The results show that GLM-5.3-Flash-Base outperforms GLM-4.5-Base overall and remains competitive with GLM-5-Base across most benchmarks.`}),`
`,(0,d.jsx)(a,{models:[`GLM-4.5-Base`,`GLM-5-Base`,`DeepSeek-V4-Flash-Base`,`GLM-5.3-Flash-Base`],highlightIndex:[3],highlightColClassName:`border-l! border-l-[rgba(0,0,0,0.3)]!`,highlightBest:!1,style:{maxWidth:`min(45rem, 100vw)`,margin:`auto`},groups:[{benchmarks:[{name:`Activated Params`,scores:[`32B`,`40B`,`13B`,`18B`]},{name:`Total Params`,scores:[`355B`,`744B`,`284B`,`320B`]}]},{benchmarks:[{name:`MMLU`,scores:[86.1,88.3,88.5,88.1]},{name:`BBH`,scores:[86.2,87.4,84.9,86.6]},{name:`HellaSwag`,scores:[87.1,88.1,85.3,87.1]},{name:`LiveCodeBench-Base`,scores:[28.1,34.4,29.9,37.6]},{name:`SimpleQA`,scores:[30,36,31.2,33.5]}]}]}),`
`,(0,d.jsx)(t.p,{children:`(Results for DeepSeek-V4-Flash-Base were evaluated using our internal evaluation framework to control for implementation differences)`}),`
`,(0,d.jsx)(t.h2,{children:`Visual Intelligence in the Coding Loop`}),`
`,(0,d.jsx)(t.p,{children:`Visual coding is not just about processing images. It expands the boundary of what coding can reach. For tasks such as frontend development, game development, and 3D simulation, the final output is not code alone, but an interface, an interaction, or a world experienced by the user. Many failures only surface through rendering, interaction, or playtesting. CUA further extends coding beyond programmable systems into visible and interactive environments. Vision therefore needs to be natively integrated into the model, enabling it to decide when to observe and use visual feedback to guide subsequent actions.`}),`
`,(0,d.jsx)(t.p,{children:`We develop data synthesis pipelines for visual coding, with a focus on self-visual judgment and test-time improvement. The resulting trajectories require the model to interact with environments, inspect its own outputs, and refine them iteratively. For frontend coding, we also explored reinforcement learning with environment feedback and further strengthened GUI judgment through agent-based verification grounded in real user flows. This extends validation beyond functional correctness to the rendered and interactive product.`}),`
`,(0,d.jsx)(t.p,{children:(0,d.jsx)(t.strong,{children:`Code lets the model build and change the world. Vision lets it enter the world people see and use.`})}),`
`,(0,d.jsxs)(`div`,{style:{display:`flex`,gap:10},children:[(0,d.jsxs)(`div`,{style:{width:`48%`},children:[(0,d.jsx)(`img`,{src:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/SyYfF83Pze.jpg`,style:{width:`100%`}}),(0,d.jsx)(`div`,{style:{textAlign:`center`,fontSize:14,color:`rgba(0, 0, 0, 0.7)`},children:`Initial Version with Layout Issues`})]}),(0,d.jsxs)(`div`,{style:{width:`48%`},children:[(0,d.jsx)(`img`,{src:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/Hy1xDIhwzl.jpg`,style:{width:`100%`}}),(0,d.jsx)(`div`,{style:{textAlign:`center`,fontSize:14,color:`rgba(0, 0, 0, 0.7)`},children:`After Visual Self-Verification`})]})]}),`
`,(0,d.jsx)(t.h2,{children:`Beyond Coding -- Your Partner at Work`}),`
`,(0,d.jsx)(t.p,{children:`Coding capabilities provide an important foundation for intelligent knowledge work, while visual intelligence extends these capabilities to a broader range of professional tasks. A substantial portion of professional activities involves interpreting heterogeneous visual and structured information, including documents, spreadsheets, presentations, dashboards, interfaces, and meeting artifacts.`}),`
`,(0,d.jsx)(t.p,{children:`Visual intelligence extends the model’s capabilities beyond code-centric environments by enabling it to jointly reason over textual, visual, and structural context. Rather than requiring users to explicitly translate their working environment into textual instructions, the model can directly interpret the artifacts associated with a task and identify relevant information. It can also assess its own outputs against the visual context and intended outcome, enabling more effective self-verification and refinement — including stronger judgments of presentation quality and aesthetics.`}),`
`,(0,d.jsx)(t.p,{children:`These capabilities become particularly evident in the following examples of professional workflows.`}),`
`,(0,d.jsx)(p,{examples:[{title:`Eight Planets of the Solar System`,href:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/Eight_Worlds_Planetary_Archive.pdf`},{title:`2026 Hospitality Responsibility Report`,href:`https://z-cdn-media.chatglm.cn/prompts-rich-media-resources/5.3-flash-blog/COMMON_ROOM_STAY_WITH_CARE_2026.pdf`}]}),`
`,(0,d.jsx)(t.h2,{children:`Serving at Scale on Chinese AI Chips`}),`
`,(0,d.jsx)(t.p,{children:`Over the past week, we have served GLM-5.3-Flash on a large-scale cluster of Chinese AI chips, supported by a high-bandwidth interconnect and a serving stack optimized for the underlying hardware.`}),`
`,(0,d.jsx)(t.p,{children:`To overcome the relatively limited compute and memory capacity of individual chips, we built a dedicated inference engine for this architecture on top of SGLang. Notably, this effort was accelerated by our GLM-5.3-powered infrastructure agent, which assisted engineers in developing and optimizing kernels, diagnosing performance bottlenecks, and improving the serving stack — creating a feedback loop in which the model helped optimize the system serving the model itself.`}),`
`,(0,d.jsx)(t.p,{children:`These chips are primarily constrained by memory capacity and bandwidth, especially when supporting context lengths of up to one million tokens. This calls for aggressive memory optimization, including compute-for-bandwidth and communication-for-bandwidth techniques tailored to the underlying architecture. Our stack combines intra-node tensor parallelism for Linear Attention and the LM head, ReplaySSM, W8A8 quantization, hybrid INT8/FP8/BF16 cache quantization, and Layer Split.`}),`
`,(0,d.jsx)(t.p,{children:`At cluster scale, our production-grade Encode–Prefill–Decode (EPD) disaggregated architecture separates multimodal encoding, prompt prefill, and token-by-token decoding into independently scheduled and scalable worker pools, enabling efficient and reliable serving across tens of thousands of domestically developed accelerators.`}),`
`,(0,d.jsx)(t.p,{children:`Compared with our initial baseline on the same hardware, we achieved a 3× improvement in end-to-end serving performance, reaching hardware efficiency and per-token cost comparable to mainstream NVIDIA GPUs. This demonstrates that Chinese chips can support frontier-model inference efficiently and economically at scale.`}),`
`,(0,d.jsx)(t.h2,{children:`Conclusion`}),`
`,(0,d.jsx)(t.p,{children:`GLM-5.3-Flash shows that frontier intelligence does not have to come at frontier cost. This is not the result of any single trick, but of three layers working together: an architecture that delivers stronger capability from less compute, a richer multimodal pre-training corpus, and infrastructure co-designed with inference hardware. We are now scaling this recipe to larger models — GLM-5.3-Flash pushes the cost-performance frontier, and the lessons from building it are already shaping our next frontier model.`}),`
`,(0,d.jsx)(t.h2,{children:`Getting started with GLM-5.3-Flash`}),`
`,(0,d.jsxs)(t.p,{children:[`We've rolled out GLM-5.3-Flash to all GLM Coding Plan users. GLM-5.3-Flash gives you `,(0,d.jsx)(t.strong,{children:`3x`}),` the usable quota of GLM-5.3. Try `,(0,d.jsx)(t.strong,{children:`GLM-5.3-Flash`}),` in `,(0,d.jsx)(t.a,{href:`https://z.ai/subscribe`,children:`z.ai/subscribe`}),`.`]}),`
`,(0,d.jsxs)(t.p,{children:[`Unlock GLM-5.3-Flash's multimodal capabilities in `,(0,d.jsx)(t.a,{href:`https://zcode.z.ai`,children:`ZCode`}),` with `,(0,d.jsx)(t.strong,{children:`Browser Use`}),` and `,(0,d.jsx)(t.strong,{children:`Computer Use`}),`: the agent clicks through and visually verifies web pages, and operates your desktop apps.`]}),`
`,(0,d.jsxs)(t.p,{children:[`The model weights of GLM-5.3-Flash are publicly available on `,(0,d.jsx)(t.a,{href:`https://huggingface.co/zai-org/GLM-5.3-Flash`,children:`HuggingFace`}),`. For local deployment, GLM-5.3-Flash currently supports inference frameworks including SGLang, vLLM and TokenSpeed. Others will be ready soon.`]}),`
`,(0,d.jsx)(a,{models:[`GLM-5.3-Flash`,`GLM-5.2`,`DeepSeek-V4-Vision-Exp`,`Opus 4.8`,`GPT-5.6 Terra`,`Gemini 3.7 Flash`],highlightIndex:[0],highlightBest:!0,groups:[{name:`Coding`,benchmarks:[{name:`Terminal Bench 2.1`,scores:[84.3,81,83.9,85,87.4,85.8]},{name:`DeepSWE (v1.1)`,scores:[63.4,46.2,59.3,58,69.6,65.3]},{name:`NL2Repo`,scores:[56.3,48.9,57.7,69.7,null,null]}]},{name:`Agentic`,benchmarks:[{name:`Toolathlon Verified`,scores:[78.4,59.9,75.9,76.2,74.9,null]},{name:`AutomationBench (v1.0.6)`,scores:[48.8,26.2,38.8,41,37.2,52.3]},{name:`Agents' Last Exam`,scores:[26.3,20.4,27.3,27,28,null]},{name:`HLE w/ Tools`,scores:[55.3,54.7,55.1,57.9,null,null]},{name:`GDPval-AA v2`,scores:[1773,1504,1675,1582,1571,1527]}]},{name:`Vision`,benchmarks:[{name:`OfficeQA Pro`,scores:[62.4,null,57.9,48.9,null,null]},{name:`CharXiv Reasoning (w/ Tools)`,scores:[89.4,null,80.4,89.9,88,88.7]},{name:`Chartography (w/ Tools)`,scores:[78,null,64.3,75,68,65]},{name:`BabyVision`,scores:[53.4,null,35.1,46.8,61.6,70.9]},{name:`MVbench`,scores:[77.8,null,69.4,67.1,75,82.2]},{name:`MMVU`,scores:[80.5,null,72.7,67.4,75.8,82.3]}]}]}),`
`,(0,d.jsx)(t.h2,{children:`Footnotes`}),`
`,(0,d.jsxs)(t.ul,{children:[`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`HLE w/ tools (full set)`}),`: We use sampling parameters of `,(0,d.jsx)(t.code,{children:`temperature=1.0`}),` and `,(0,d.jsx)(t.code,{children:`top_p=0.95`}),` for evaluation, with a maximum generation length of `,(0,d.jsx)(t.code,{children:`163,840`}),` tokens. The evaluation is conducted with a maximum context length of `,(0,d.jsx)(t.code,{children:`300,000`}),` tokens, using a context management strategy. We use GPT-5.6-luna (medium) as the judge model.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`NL2Repo`}),`: We evaluated NL2Repo with temperature=1.0, top_p=1.0, and max_new_tokens=64k under 1M context. To prevent hacking, we use rule-based and a LLM-based judgement to prevent malicious behaviors (e.g., unauthorized pip or curl operations).`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`DeepSWE`}),`: We run DeepSWE using the mini-swe-agent harness with `,(0,d.jsx)(t.code,{children:`temperature=0.95`}),`, `,(0,d.jsx)(t.code,{children:`top_p=1.0`}),`, `,(0,d.jsx)(t.code,{children:`timeout=6h`}),` and 400K context.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`Terminal-Bench 2.1`}),`: We evaluate in Claude Code 2.1.207 with temperature=1.0, top_p=1, max_new_tokens=65536 with 6h timeout.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`Agent’s Last Exam`}),`: We evaluate ALE using the official evaluation protocol with the Claude Code harness (reasoning effort=max, 1M context, and 64K maximum output). Tool Search is disabled, and results are scored by the official ALE evaluators.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`Toolathlon Verified`}),`: We obtain all results via the official evaluation service and report pass@1 averaged over 3 independent runs.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`AutomationBench`}),`: We evaluate on AutomationBench `,(0,d.jsx)(t.strong,{children:`v1.0.6`}),`, incorporating the fix for the `,(0,d.jsx)(t.code,{children:`null`}),`-type handling issue introduced in `,(0,d.jsx)(t.a,{href:`https://github.com/zapier/AutomationBench/pull/13`,children:`PR #13`}),`.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`GDPval-AA v2`}),`: Models are evaluated by Artificial Analysis.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`BabyVision`}),`: We use temperature=1.0, top_p=0.95, and a maximum context length of 164K tokens. We resize the input images such that their shorter side is at least 1.5K pixels, consistent with other baselines.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`OfficeQA Pro`}),`: We evaluate the agent on the Treasury Bulletin PDF corpus without providing access to embedded text. We use a temperature of 1.0, top_p of 0.95, and a maximum context length of 512K tokens.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`CharXiv Reasoning`}),`: We use temperature=1.0, top_p=0.95, and a maximum context length of 256K tokens.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`Chartography`}),`: We use temperature=1.0, top_p=0.95, and a maximum context length of 256K tokens.`]}),`
`,(0,d.jsxs)(t.li,{children:[(0,d.jsx)(t.strong,{children:`MVBench and MMVU`}),`: We use temperature=1.0, top_p=0.95, and a maximum context length of 256K tokens. For models that natively accept video input, such as Gemini 3.7 Flash, we feed the raw video directly for evaluating. For models that do not support video input, we adapt a default 1 fps frame‑extraction strategy. If the total number of extracted frames exceeds the API’s maximum limit, we perform uniform frame‑sampling across the video up to this maximum frame count.`]}),`
`]})]})}function h(e={}){let{wrapper:t}=e.components||{};return t?(0,d.jsx)(t,{...e,children:(0,d.jsx)(m,{...e})}):m(e)}(0,l.createRoot)(document.getElementById(`root`)).render((0,d.jsx)(u.StrictMode,{children:(0,d.jsx)(o,{date:`2026-08-26`,title:`GLM-5.3-Flash: Frontier Intelligence, Flash Cost`,document:`https://docs.z.ai/guides/llm/glm-5.3-flash`,tryZai:!1,callZai:!0,subscribeZai:!0,zcode:!0,huggingface:`https://huggingface.co/zai-org/GLM-5.3-flash`,children:(0,d.jsx)(c,{children:(0,d.jsx)(r,{en:h,components:s})})})}));